import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SmoothScroll from "@/components/SmoothScroll";
import CustomCursor from "@/components/CustomCursor";
import { CurveLoader } from "@/components/CurveLoader";
import DynamicFavicon from "@/components/DynamicFavicon";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased bg-[#656766] text-zinc-900`}
        suppressHydrationWarning
      >
        <CurveLoader />
        <SmoothScroll />
        <CustomCursor />
        <DynamicFavicon />
        {children}
      </body>
    </html>
  );
}
